In [111]:
import pandas as pd
path = 'reports/crabby_councilperson/Consuela_the_demonic/trade_history.csv'
pd.set_option('display.max_rows',500)

In [112]:

df = pd.read_csv(path, index_col=0)
df

,Date,price,size,value,side,motive,pnl,fees,balance,trade_count,position side
0,2019-08-17 16:30:00,2.382200,NaN,NaN,NaN,INIT,NaN,NaN,1000.000000,0,NaN
1,2019-08-18 20:30:00,2.495938,200.325451,500.000000,buy,open,NaN,0.100000,999.900000,1,long
2,2019-08-18 22:30:00,2.487501,200.325451,498.309821,sell,tp,-1.690179,0.099662,998.110159,1,long
3,2019-08-18 23:00:00,2.481532,201.107652,499.055080,buy,open,NaN,0.099811,998.010348,2,long
4,2019-08-18 23:30:00,2.500350,201.107652,502.839523,sell,tp,3.784443,0.100568,1001.694223,2,long
...,...,...,...,...,...,...,...,...,...,...,...
1234,2019-11-29 21:30:00,2.332236,451.874253,1053.877250,sell,tp,2.010581,0.210775,2105.322770,617,long
1235,2019-11-29 22:00:00,2.327809,452.211241,1052.661385,buy,open,NaN,0.210532,2105.112237,618,long
1236,2019-11-29 22:30:00,2.333050,452.211241,1055.031626,sell,tp,2.370241,0.211006,2107.271472,618,long
1237,2019-11-29 23:00:00,2.330024,452.199484,1053.635736,buy,open,NaN,0.210727,2107.060745,619,long
1238,2019-11-29 23:30:00,2.338576,452.199484,1057.502998,sell,tp,3.867262,0.211501,2110.716507,619,long

In [113]:
motive = None
for n in range(len(df)):
    # print(n)
    # print(motive)
    # print(df['motive'].iloc[n])
    if df['motive'].iloc[n] == motive:
        print('problem at index {}'.format(n))
        print(df.iloc[n-1:n+1])
        break
    else:
        motive = df['motive'].iloc[n]

In [114]:
df.loc[df['position side'] == 'short']

,Date,price,size,value,side,motive,pnl,fees,balance,trade_count,position side
29,2019-08-20 12:30:00,2.434696,203.865061,496.349362,sell,open,NaN,0.099270,992.599454,15,short
30,2019-08-21 03:30:00,2.295143,203.865061,467.899414,buy,tp,28.449948,0.093580,1020.955822,15,short
31,2019-08-21 05:00:00,2.322484,219.798253,510.477911,sell,open,NaN,0.102096,1020.853726,16,short
32,2019-08-21 10:00:00,2.206192,219.798253,484.917140,buy,tp,25.560771,0.096983,1046.317514,16,short
33,2019-08-21 14:00:00,2.220493,235.604783,523.158757,sell,open,NaN,0.104632,1046.212882,17,short
...,...,...,...,...,...,...,...,...,...,...,...
1218,2019-11-28 11:00:00,2.230444,460.016656,1026.041472,buy,tp,-4.738945,0.205208,2037.456641,609,short
1219,2019-11-28 12:00:00,2.226041,457.641356,1018.728320,sell,open,NaN,0.203746,2037.252895,610,short
1220,2019-11-28 12:30:00,2.231302,457.641356,1021.136153,buy,tp,-2.407833,0.204227,2034.640835,610,short
1221,2019-11-28 13:00:00,2.223188,457.595393,1017.320418,sell,open,NaN,0.203464,2034.437371,611,short
1222,2019-11-28 14:00:00,2.226802,457.595393,1018.974355,buy,tp,-1.653937,0.203795,2032.579639,611,short