In [91]:
import pandas as pd
path = 'test_trade_hist.csv'
pd.set_option('display.max_rows',250)

In [92]:

df = pd.read_csv(path, index_col=0)
df

,Date,price,size,value,side,motive,pnl,fees,balance,trade_count,position side
0,2021-11-09 04:20:00,2.102100,NaN,NaN,NaN,INIT,NaN,NaN,1000.000000,0,NaN
1,2021-11-09 04:40:00,2.078752,240.528925,500.000000,buy,open,NaN,0.100000,999.900000,1,long
2,2021-11-09 04:45:00,2.129559,240.528925,512.220487,sell,tp,12.220487,0.102444,1012.018043,1,long
3,2021-11-09 04:46:00,2.132511,237.283175,506.009021,sell,open,NaN,0.101202,1011.916841,2,short
4,2021-11-09 05:35:00,2.135621,237.283175,506.746910,buy,tp,-0.737889,0.101349,1011.077603,2,short
...,...,...,...,...,...,...,...,...,...,...,...
607,2021-11-16 00:34:00,2.811910,154.624371,434.789802,sell,open,NaN,0.086958,869.492647,304,short
608,2021-11-16 00:50:00,2.789484,154.624371,431.322249,buy,tp,3.467554,0.086264,872.873936,304,short
609,2021-11-16 00:51:00,2.787011,156.596811,436.436968,buy,open,NaN,0.087287,872.786649,305,long
610,2021-11-16 01:48:00,2.742371,156.596811,429.446503,sell,tp,-6.990465,0.085889,865.710294,305,long
611,2021-11-16 02:02:00,2.719365,159.175090,432.855147,buy,open,NaN,0.086571,865.623723,306,long

In [93]:
df = df.loc[df['motive'] == "open"]

In [94]:
idx = df.index.to_list()

In [95]:
for n in range(len(idx)):
    if n == idx[n-1]+1:
        print('ERROR')